server:
  port: 10005

spring:
  application:
    name: user-service
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      # none: 미생성, create: 항상 다시 생성, create-drop: 시작시 생성후 종료시 제거, update: 추가 테이블/컬럼 생성(삭제하진 않음), verify: 비교
      ddl-auto: create    
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false # lazy loading으로 인해 json serialize 오류 방지
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user-created: topic-user-created
      user-modified: topic-user-modified 
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/ # eureka server 주소

security:
  oauth2:
    client:
      id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key # authorization server와 동일하게 셋팅해야 함