spring:
  h2:
    console: # h2-console 사용
      enabled: true
      path: /h2-console
  jpa: # jpa sql 로깅
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false # lazy loading으로 인해 json serialize 오류 방지
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user-created: topic-user-created
      user-modified: topic-user-modified       
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka server 주소